# Generated by Django 5.0.2 on 2024-02-23 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_rename_flights_flight_passenger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='passengers',
            new_name='flights',
        ),
    ]
